In [1]:
print("hello")

hello


In [ ]:
a[]=int(input("enter the number"))

if a==a[::-1]:
    print("is palidrome")
else:
    print("not a palidrome")

SyntaxError: invalid syntax (2798348359.py, line 1)

In [2]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

  # 120

In [1]:
print(factorial(7))

NameError: name 'factorial' is not defined

In [1]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
a2=np.ones((2,3))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
print(type(a2))

<class 'numpy.ndarray'>


In [16]:
a3=np.zeros((2,3,4))
print(a3)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [32]:
a=np.arange(1,11)


In [34]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
l1=[1,2,3,4]

l1.append(6)

print(l1)

l1.insert(2,8)
print(l1)

l1.pop()
print(l1)

l1.remove(8)
print(l1)

[1, 2, 3, 4, 6]
[1, 2, 8, 3, 4, 6]
[1, 2, 8, 3, 4]
[1, 2, 3, 4]


In [ ]:
l2=[1,5,7,'re','te','el']



l2[-3:-2:]

['re']

In [1]:
#reverse a string

def rev(s):
    return s[::-1]

s=input("enter the string")
r=rev(s)
print("first string is",s)
print("rev string is",r)

first string is hellow
rev string is wolleh
